### ISSUE TITLE
YAY!

### ISSUE THREAD

**Issue by vadis365** [vadis365/Transport-Terminal#20]
We got added to RR!
http://imgur.com/vBQsyom

**Comment by vadis365** [comment]
Update - Yogscast are using RR 3 - fingers crossed (Duncan already mentioned the Erebus)

**Comment by ganymedes01** [comment]
That's awesome! :D TT deserves it, such a useful mod ;3

Anyway, how have you been? :3 I ought to join skype at some point... lol
